import React, { useEffect } from 'react';
import Head from 'next/head';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import { useDispatch } from 'react-redux';
import { useSelector } from '../state/store';
import { getSurveys } from '../state/actions/getSurveys';
import { setSurveyToShow } from '../state/actions/setSurveyToShow';
import { newDraftSurvey, updateDraftSurvey, createSurvey as actionCreateSurvey, cleanDraftSurvey as actionCleanDraftSurvey } from '../state/actions/newDraftSurvey';
import Suverys from '../components/surveys';
import DraftSuverys from '../components/draftSurvey';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const dispatch = useDispatch();

  const selectSurvey = (id: string) => {
    dispatch(setSurveyToShow(id));
  }

  const newSurvey = () => {
    dispatch(newDraftSurvey());
  }

  const updateSuvery = (type: string, value: string) => {
    dispatch(updateDraftSurvey(type, value));
  }

  const createSurvey = () => {
    dispatch(actionCreateSurvey());
  }

  const cleanDraftSurvey = () => {
    dispatch(actionCleanDraftSurvey());
  }

  const surveys  = useSelector(store => store.Surveys);
  const surveyToShow  = useSelector(store => store.Surveys.surveyToShow);
  const draftSurvey  = useSelector(store => store.Surveys.draftSurvey);

  // useEffect(() => {
  //   dispatch(getSurveys());
  // }, [getSurveys]);

  return (
    <>
      <Head>
        <title>Tienda de juegos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="mx-auto flex w-3/4 gap-x-3 py-[100px]">
        <DraftSuverys
          draftSurvey={draftSurvey}
          updateSuvery={updateSuvery}
          createSurvey={createSurvey}
          cleanDraftSurvey={cleanDraftSurvey}
        />
        <Suverys
          surveys={surveys.surveys?.surveys}
          surveyToShow={surveyToShow}
          selectSurvey={selectSurvey}
          newSurvey={newSurvey}
          draftSurvey={draftSurvey}
          />
        </div>
      </main>
    </>
  )
}
